name: "KScript Action"
author: 'Maxim Bîrcu'
description: "Github action to run KScript files"
inputs:
  kotlin-script:
    description: "A path or a url to the KScript file to be run"
    required: true

  kotlin-version:
    description: "Kotlin version - choose from the ones available in sdkman"
    required: false

  kscript-version:
    description: "Kscript version - choose from the ones available in sdkman"
    required: false

branding:
  icon: code
  color: yellow

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.kotlin-version }}
    - ${{ inputs.kscript-version }}
    - ${{ inputs.kotlin-script }}
